//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class HL7Versions {
    
    private HL7VersionsHL7Version[] hL7VersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HL7Version")]
    public HL7VersionsHL7Version[] HL7Version {
        get {
            return this.hL7VersionField;
        }
        set {
            this.hL7VersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7Version {
    
    private string versionField;
    
    private HL7VersionsHL7VersionDatatype[] datatypesField;
    
    private HL7VersionsHL7VersionSegment[] segmentsField;
    
    private HL7VersionsHL7VersionGroup[] groupsField;
    
    private HL7VersionsHL7VersionMessage[] messagesField;
    
    private HL7VersionsHL7VersionEntry[] mappingField;
    
    private HL7VersionsHL7VersionGrammar[] grammarsField;
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Datatype", IsNullable=false)]
    public HL7VersionsHL7VersionDatatype[] Datatypes {
        get {
            return this.datatypesField;
        }
        set {
            this.datatypesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
    public HL7VersionsHL7VersionSegment[] Segments {
        get {
            return this.segmentsField;
        }
        set {
            this.segmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Group", IsNullable=false)]
    public HL7VersionsHL7VersionGroup[] Groups {
        get {
            return this.groupsField;
        }
        set {
            this.groupsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
    public HL7VersionsHL7VersionMessage[] Messages {
        get {
            return this.messagesField;
        }
        set {
            this.messagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Entry", IsNullable=false)]
    public HL7VersionsHL7VersionEntry[] Mapping {
        get {
            return this.mappingField;
        }
        set {
            this.mappingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Grammar", IsNullable=false)]
    public HL7VersionsHL7VersionGrammar[] Grammars {
        get {
            return this.grammarsField;
        }
        set {
            this.grammarsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionDatatype {
    
    private string nameField;
    
    private string descriptionField;
    
    private HL7VersionsHL7VersionDatatypeComposite[] compositesField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Composite", IsNullable=false)]
    public HL7VersionsHL7VersionDatatypeComposite[] Composites {
        get {
            return this.compositesField;
        }
        set {
            this.compositesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionDatatypeComposite {
    
    private string nameField;
    
    private string descriptionField;
    
    private ushort tableField;
    
    private bool tableFieldSpecified;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public ushort Table {
        get {
            return this.tableField;
        }
        set {
            this.tableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TableSpecified {
        get {
            return this.tableFieldSpecified;
        }
        set {
            this.tableFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionSegment {
    
    private string nameField;
    
    private string descriptionField;
    
    private HL7VersionsHL7VersionSegmentFields fieldsField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public HL7VersionsHL7VersionSegmentFields Fields {
        get {
            return this.fieldsField;
        }
        set {
            this.fieldsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionSegmentFields {
    
    private HL7VersionsHL7VersionSegmentFieldsField[] fieldField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Field")]
    public HL7VersionsHL7VersionSegmentFieldsField[] Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionSegmentFieldsField {
    
    private byte orderField;
    
    private string typeField;
    
    private bool requiredField;
    
    private byte repeationsField;
    
    private uint lengthField;
    
    private string tableField;
    
    private string descriptionField;
    
    /// <remarks/>
    public byte Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public bool Required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    public byte Repeations {
        get {
            return this.repeationsField;
        }
        set {
            this.repeationsField = value;
        }
    }
    
    /// <remarks/>
    public uint Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    public string Table {
        get {
            return this.tableField;
        }
        set {
            this.tableField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionGroup {
    
    private string nameField;
    
    private HL7VersionsHL7VersionGroupField[] fieldsField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
    public HL7VersionsHL7VersionGroupField[] Fields {
        get {
            return this.fieldsField;
        }
        set {
            this.fieldsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionGroupField {
    
    private byte orderField;
    
    private string typeField;
    
    private bool requiredField;
    
    private bool repeatingField;
    
    /// <remarks/>
    public byte Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public bool Required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    public bool Repeating {
        get {
            return this.repeatingField;
        }
        set {
            this.repeatingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionMessage {
    
    private string nameField;
    
    private string chapterField;
    
    private HL7VersionsHL7VersionMessageField[] fieldsField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Chapter {
        get {
            return this.chapterField;
        }
        set {
            this.chapterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
    public HL7VersionsHL7VersionMessageField[] Fields {
        get {
            return this.fieldsField;
        }
        set {
            this.fieldsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionMessageField {
    
    private byte orderField;
    
    private string typeField;
    
    private bool requiredField;
    
    private bool repeatingField;
    
    /// <remarks/>
    public byte Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public bool Required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    public bool Repeating {
        get {
            return this.repeatingField;
        }
        set {
            this.repeatingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionEntry {
    
    private string typeField;
    
    private string eventField;
    
    private string structureField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Event {
        get {
            return this.eventField;
        }
        set {
            this.eventField = value;
        }
    }
    
    /// <remarks/>
    public string Structure {
        get {
            return this.structureField;
        }
        set {
            this.structureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionGrammar {
    
    private string messageField;
    
    private string chapterField;
    
    private HL7VersionsHL7VersionGrammarSegment[] segmentsField;
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string Chapter {
        get {
            return this.chapterField;
        }
        set {
            this.chapterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
    public HL7VersionsHL7VersionGrammarSegment[] Segments {
        get {
            return this.segmentsField;
        }
        set {
            this.segmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HL7VersionsHL7VersionGrammarSegment {
    
    private string nameField;
    
    private string groupField;
    
    private bool requiredField;
    
    private bool repeatingField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    public bool Required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    public bool Repeating {
        get {
            return this.repeatingField;
        }
        set {
            this.repeatingField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}
